- name: Demo on Conditions
  hosts: all
  connection: local
  tasks:
    - name: Print Fruit Name
      ansible.builtin.debug:
        msg: Fruit Name - Apple
      when: fruit is true
    - name: Print vegetable Name
      ansible.builtin.debug:
        msg: Vegetable Name - Carrot
      when: fruit is true