- name: Variable Types
  hosts: localhost
  connection: local
  vars:
    fruit_name: Apple # string
    quantity: 100 # number
    for_sale: "true" # boolean, Booleans Supported by ansible are true/false yes/no,Boolean becomes string if you quote it.

  tasks:
    - name: Print
      ansible.builtin.debug:
        msg: Fruit Name - {{fruit_name}}, Quantity - {{quantity}}
      when: "for_sale"
