- name: Demo On Loops
  hosts: local
  connection: localhost
  vars:
    fruits:
      - apple
      - banana
  tasks:
    - name: Print Fruits
      ansible.builtin.debug:
        msg: Fruit Name - "{{ item }}"
      loop: "{{ fruits }}"

    - name: Print Fruits with Local Values
      ansible.builtin.debug:
        msg: Fruit Name - "{{ item }}"
      loop:
        - mango
        - berries
